### ISSUE TITLE
VLANs plugin not working

### ISSUE THREAD

**Issue by GeComDohlad** [dubbelj/librenms-plugin-vlan-brief-overview#4]
[VLANs caused an error and was disabled, please check with the plugin creator to fix the error. The error can be found in logs/librenms.log](http://XXX.XXXXXX.XX/notifications/)
this message i get from LibreNMS
this is from librenms.log
[2022-12-19T10:48:00.770914+01:00] production.ERROR: Error: Undefined constant "LibreNMS\Plugins\rootBridge" in /opt/librenms/html/plugins/VLANs/VLANs.php:31

could you some help me ?

**Comment by sorano** [comment]
Fixed in #3 . Update code and close this issue please.
